<a href="https://colab.research.google.com/github/HaksuChang/python_programming/blob/main/LoadData(Pandas)(%ED%95%99%EC%83%9D%EC%9A%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Introduction to Pandas Python</h1>

<h2 id="pandas">Introduction of <code>Pandas</code></h2>

In [2]:
# Python code demonstrate creating
# DataFrame from dict narray / lists
# By default addresses.

import pandas as pd

# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}

# Create DataFrame
df = pd.DataFrame(data)

# Print the output.
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

#Dataframe

In [3]:
# Read data from CSV file (I will )
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [4]:

csv_path = '/content/gdrive/My Drive/Colab Notebooks/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)

We can use the method <code>head()</code> to examine the first five rows of a dataframe:

In [5]:
# Print first five rows of the dataframe
#df.head()

# Print last five rows of the dataframe
df.tail()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

 We use the path of the excel file and the function <code>read_excel</code>. The result is a data frame as before:

In [6]:
# Read data from Excel File and print the first five rows

xlsx_path = '/content/gdrive/My Drive/Colab Notebooks/TopSellingAlbums.xlsx'

df1 = pd.read_excel(xlsx_path)
df1.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,00:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,00:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,00:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,00:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0

We can access the column <b>Length</b> and assign it a new dataframe <b>x</b>:

In [7]:
# Access to the column Length

x = df[['Genre']]
x

                         Genre
0               pop, rock, R&B
1                    hard rock
2             progressive rock
3               R&B, soul, pop
4  hard rock, progressive rock
5   rock, soft rock, folk rock
6                        disco
7                    soft rock

 The process is shown in the figure:

<hr>

<h2 id="data">Viewing Data and Accessing Data</h2>

You can also get a column as a series. You can think of a Pandas series as a 1-D dataframe. Just use one bracket:

In [8]:
# Get the column as a series

x = df['Length']
x

0    0:42:19
1    0:42:11
2    0:42:49
3    0:57:44
4    0:46:33
5    0:43:08
6    1:15:54
7    0:40:01
Name: Length, dtype: object

You can also get a column as a dataframe. For example, we can assign the column <b>Artist</b>:

In [ ]:
# Get the column as a dataframe

x = df[['Artist']]
x

            Artist
0  Michael Jackson
1            AC/DC
2       Pink Floyd
3  Whitney Houston
4        Meat Loaf
5           Eagles
6         Bee Gees
7    Fleetwood Mac

You can do the same thing for multiple columns; we just put the dataframe name, in this case, <code>df</code>, and the name of the multiple column headers enclosed in double brackets. The result is a new dataframe comprised of the specified columns:

In [ ]:
# Access to multiple columns

y = df[['Artist','Length','Genre']]
y

            Artist   Length                        Genre
0  Michael Jackson  0:42:19               pop, rock, R&B
1            AC/DC  0:42:11                    hard rock
2       Pink Floyd  0:42:49             progressive rock
3  Whitney Houston  0:57:44               R&B, soul, pop
4        Meat Loaf  0:46:33  hard rock, progressive rock
5           Eagles  0:43:08   rock, soft rock, folk rock
6         Bee Gees  1:15:54                        disco
7    Fleetwood Mac  0:40:01                    soft rock

The process is shown in the figure:

One way to access unique elements is the <code>iloc</code> method, where you can access the 1st row and the 1st column as follows:

In [ ]:
# Access the value on the first row and the first column

df.iloc[0, 0] #첫번째 행, 첫번째 열

'Michael Jackson'

You can access the 2nd row and the 1st column as follows:

In [ ]:
# Access the value on the second row and the first column

df.iloc[1,0] #두번째 행, 첫번째 열

'AC/DC'

You can access the 1st row and the 3rd column as follows:

In [ ]:
# Access the value on the first row and the third column

df.iloc[0,2]

1982

You can access the column using the name as well, the following are the same as above:

In [ ]:
# Access the column using the name

df.loc[0, 'Artist']

'Michael Jackson'

In [ ]:
# Access the column using the name

df.loc[1, 'Artist']

'AC/DC'

In [ ]:
# Access the column using the name

df.loc[0, 'Released']

1982

In [ ]:
# Access the column using the name

df.loc[1, 'Released']

1980

You can perform slicing using both the index and the name of the column:

In [ ]:
# Slicing the dataframe

df.iloc[0:2, 0:3] #row, column sequence

            Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

In [ ]:
# Slicing the dataframe using name

df.loc[0:2, 'Artist':'Released'] #iloc, loc의 차이점이 있음...

            Artist                      Album  Released
0  Michael Jackson                   Thriller      1982
1            AC/DC              Back in Black      1980
2       Pink Floyd  The Dark Side of the Moon      1973

In [ ]:
# iterating over rows using iterrows() function
for i, j in df.iterrows():
    print(i, j)
    print()

In [ ]:
#Where function --> data science에서 가장 많이 사용하는 기능

# making boolean series for the artist name
#filter1 = df["Artist"]=="Michael Jackson"
# making boolean series for Length
filter2 = df["Claimed Sales (millions)"]>40

# filtering data on basis of both filters
df.where(filter2)

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982.0,0:42:19,"pop, rock, R&B",46.0,65.0,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980.0,0:42:11,hard rock,26.1,50.0,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973.0,0:42:49,progressive rock,24.2,45.0,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992.0,0:57:44,"R&B, soul, pop",27.4,44.0,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977.0,0:46:33,"hard rock, progressive rock",20.6,43.0,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976.0,0:43:08,"rock, soft rock, folk rock",32.2,42.0,17-Feb-76,NaN,7.5
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<hr>

<h2 id="quiz">Quiz on DataFrame</h2>

In [9]:
q = df[['Rating']]
q

   Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5

Double-click __here__ for the solution.

<!-- Your answer is below:
q = df[['Rating']]
q
-->

Double-click __here__ for the solution.

<!-- Your answer is below:
q = df[['Rating']]
q
-->

Assign the variable <code>q</code> to the dataframe that is made up of the column <b>Released</b> and <b>Artist</b>:

In [ ]:
q = df[['Released', 'Artist']]
q

   Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

Access the 2nd row and the 3rd column of <code>df</code>:

In [ ]:
df.iloc[1, 2]

1980

<hr>